apiVersion: v1
kind: Service
metadata:
  name: moj-nginx-service
  namespace: ppa-ns
spec:
  type: LoadBalancer # <-- Zmiana tutaj
  selector:
    creator: created-by-ppa
  ports:
    - protocol: TCP
      port: 80 # Słuchamy na standardowym porcie HTTP
      targetPort: 80
