apiVersion: v1
kind: Pod
metadata:
  name: pod-z-secret
  namespace: k8s-wprawki
  labels:
    creator: created-by-XXX
    app: the-best-apka
    env: prod
spec:
  volumes:
    - name: tajne-tls
      secret:
        secretName: myapp-secret-tls
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - mountPath: /secret/
          name: tajne-tls
      env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: DB_URL
        - name: UUID
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: UUID

      ports:
        - containerPort: 80
      # livenessProbe:
      #   exec:
      #     command:
      #       - test
      #       - -f
      #       - /usr/share/nginx/html/healthy
