apiVersion: v1
kind: Pod
metadata:
  name: moj-pod-nginx
  namespace: ppa-ns
  labels:
    creator: created-by-ppa
    app: apka-ppa
    env: prod
spec:
  volumes:
    - name: wspolny-katalog
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: wspolny-katalog
          mountPath: /usr/share/nginx/html
      # livenessProbe:
      #   exec:
      #     command:
      #       - test
      #       - -f
      #       - /usr/share/nginx/html/healthy
    - name: pomocnik-do-logow
      image: alpine
      command:
        [
          "/bin/sh",
          "-c",
          "while true; do echo 'Log z aplikacji' >> /var/log/app.log; sleep 5; done",
        ]
      volumeMounts:
        - name: wspolny-katalog
          mountPath: /var/log
