apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: k8s-wprawki
  labels:
    creator: created-by-XXX
    app: the-best-apka
    env: prod

type: Opaque
stringData:
  # DB_URL: "sqlite:////var/lib/data/baza.db"
  DB_URL: "sqlite:///memory"
  # DB_URL: "sqlite:///baza.db"
  UUID: "6f92d87a-713c-11f1-81f0-bfd62ea0b32d"
