apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-configmap
  namespace: k8s-wprawki
data:
  tryb_aplikacji: "produkcja"
  max_conn: "50"
  db_config.properties: |-
    host=127.0.0.1
    port=5432
    Timeout=20

  nginx.conf: |-
    server {
        listen       81;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
